### ISSUE TITLE
> \prod_{i=1}^k H(v_i) 

### ISSUE THREAD

**Issue by xjzhao001** [toshas/torch-householder#2]
> \prod_{i=1}^k H(v_i), is that right?
Right.
Hi, toshas, your work is great, thanks!
You confirm that if we denote H(v) = I_n - v v^T / \norm{v}^2 a Householder reflection, the torch_householder_orgqr() computes \prod_{i=1}^k H(v_i), and I have two questions, one is I think H(v) = I_n – 2*v*v^T/\norm{v}^2, and the other is \prod_{i=1}^k H(v_i) means H_1* H_2*…H_(n-1) or H_(n-1)* H_(n-2)*…H_1 ? If it is H_1* H_2*…H_(n-1), it refers to Q in QR decomposition, right? But you said earlier that this is not a QR decomposition, so I feel a little confused. Hope to get your prompt reply, thank you.

**Comment by toshas** [comment]
`H(v) = I_n - 2 v v^T / \norm{v}^2` is the correct equation.
For the rest of your questions, please refer to our paper which explains this aspect in a greater detail: https://arxiv.org/pdf/2103.04217.pdf
