### ISSUE TITLE
[Noob] Can I use this somehow as a drop-in replacement for matrix_exp?

### ISSUE THREAD

**Issue by generalizedeigenvector** [toshas/torch-householder#4]
I have some code that uses **torch.matrix_exp** and would be very happy to speed it up. Is this possible using your library? I sort of lost my way trying to figure it out from the benchmarks code. Many thanks in advance?

**Comment by toshas** [comment]
Hi there, there is no definitive answer, it depends whether your target are square orthogonal matrices, or do you prune rows/columns to obtain orthogonal frames? If all you need is square matrices, then you may only benefit from torch-householder with large batch size. Just look at the diagonals of squares on this plot, and check if the batch size and matrix size tuple lands on a blue square. If it does - you will get a speed up.

![https://raw.githubusercontent.com/toshas/torch-householder/master/doc/img/benchmark_speed_MEXP_vs_HH_OURS.png](https://raw.githubusercontent.com/toshas/torch-householder/master/doc/img/benchmark_speed_MEXP_vs_HH_OURS.png)

If your end application requires non-square matrices in the first place, chances are higher that you will get a speed up. Just use the same diagram and consider a triple (batch size, matrix height, matrix width) to see if the square it corresponds to is blue or red. 

HTH, if not, feel free to ask a follow-up
