### ISSUE TITLE
Support of complex tensors

### ISSUE THREAD

**Issue by bytesnake** [toshas/torch-householder#6]
I need support for complex datatype to learn a unitary matrix. How much effort would it be to add that?

**Comment by toshas** [comment]
It depends on how much of the existing code can be re-used. These days I don't have throughput to support extensions, so a pull request with a discussion would be very welcome!

**Comment by bytesnake** [comment]
maybe it's even sufficient to just drop those guards as you are only using (badd)bmm which has added complex support recently

**Comment by bytesnake** [comment]
I will extend testing a bit and submit a PR later this week

**Comment by bytesnake** [comment]
actually solved the problem in real domain, so closing this :)
